name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint project
        run: bun run lint

      - name: Run tests
        run: bun run test

      - name: Build project
        run: bun run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "out/,public/,package.json"
          target: ${{ secrets.SERVER_TARGET_PATH }}
          strip_components: 0
